<?php

namespace Dapr\Dev;

use Dapr\Proto\Runtime\V1\DaprClient;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpFile;

/**
 * Class InterfaceBuilder
 * @package Dapr\Dev
 */
class InterfaceBuilder {
    public static function build_interfaces(): void {
        $builder = new InterfaceBuilder(DaprClient::class);
        file_put_contents(__DIR__.'/../src/lib/Client/Interfaces/V1/DaprClientInterface.php', $builder->build());
    }

    public function __construct(public string $class) {
    }

    public function build(): PhpFile {
        $class = ClassType::from($this->class);
        $class->setInterface();
        $class->setImplements([]);
        $class->removeMethod('__construct');
        foreach($class->getMethods() as $method) {
            $method->setBody(null);
        }
        foreach($class->getProperties() as $property) {
            $class->removeProperty($property->getName());
        }
        $class->setName($class->getName() . 'Interface');
        $class->setExtends([]);

        $file = new PhpFile();
        $file->addComment('This file is automatically generated by `composer build-grpc`');
        $namespace = $file->addNamespace('Dapr\Client\Interfaces\V1');
        $namespace->add($class);
        return $file;
    }
}
