# A Docker Compose file for spinning up integration tests in CI
version: "3"
services:
  placement:
    image: daprio/dapr:${DAPR_VERSION}
    command: [ "./placement","-port","50006" ]
  dev:
    image: tests:${GITHUB_SHA}
    depends_on:
      - placement
    ports:
    - 9502:80
  dev-caddy:
    image: caddy:${GITHUB_SHA}
    depends_on:
      - dev
    network_mode: service:dev
  dev-daprd:
    image: daprio/daprd:${DAPR_VERSION}
    command: [ "./daprd","-app-id","dev","-app-port","80","-placement-host-address","placement:50006","-components-path","/components" ]
    volumes:
      - ./components:/components
    depends_on:
      - dev
    network_mode: service:dev
  redis:
    image: redis:latest
