# A Docker Compose file for spinning up integration tests in CI, you can run these locally by running `make`
version: "3"
services:
  placement:
    image: daprio/dapr:${DAPR_VERSION}
    command: [ "./placement","-port","50006" ]
  dev:
    image: tests:${GITHUB_SHA}
    environment:
      DAPR_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      APP_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    depends_on:
      - placement
    ports:
    - 9502:80
  dev-caddy:
    image: caddy:${GITHUB_SHA}
    depends_on:
      - dev
    network_mode: service:dev
  dev-scheduler:
    image: daprio/scheduler:${DAPR_VERSION}
    command: ["./scheduler"]
    user: "0"
  dev-daprd:
    image: daprio/daprd:${DAPR_VERSION}
    environment:
      DAPR_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      APP_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    command: [ "./daprd","-app-id","dev","-app-port","80","-placement-host-address","placement:50006","-components-path","/components", "--scheduler-host-address", "dev-scheduler:50006" ]
    volumes:
      - ./components:/components
    depends_on:
      - dev
    network_mode: service:dev
  redis:
    image: redis:latest
