services:
  secrets-service:
    image: php-secrets-service:${GIT_SHA}
    build:
      args:
        SERVICE: secrets
      dockerfile: ../../examples/images/service.Dockerfile
      context: ../../examples/secrets
      target: production
    environment:
      SERVER_NAME: :80
  secrets-daprd:
    image: daprio/daprd:${DAPR_VERSION}
    command: [ "./daprd","-app-id","secrets","-app-port","80","-placement-host-address","placement:50006","-components-path","/components" ]
    volumes:
      - ./components:/components
    depends_on:
      - secrets-service
    network_mode: service:secrets-service
  client-service:
    image: php-secret-client-service:${GIT_SHA}
    build:
      args:
        SERVICE: client
      dockerfile: ../../examples/images/service.Dockerfile
      context: ../../examples/secrets
      target: production
    ports:
      - 8080:80
    environment:
      SERVER_NAME: :80
  client-daprd:
    image: daprio/daprd:${DAPR_VERSION}
    command: [ "./daprd","-app-id","client","-app-port","80","-placement-host-address","placement:50006" ]
    depends_on:
      - client-service
    network_mode: service:client-service
