version: "3"
services:
  secrets-service:
    image: ${DOCKER_USER}/php-secrets-service:latest
    build:
      args:
        SERVICE: secrets
      dockerfile: ../../examples/images/service.Dockerfile
      context: ../../examples/secrets
      target: production
  secrets-http:
    image: ${DOCKER_USER}/php-secrets-http:latest
    build:
      args:
        SERVICE: secrets
      dockerfile: ../../examples/images/caddy.Dockerfile
      context: ../../examples/secrets
    depends_on:
      - secrets-service
    network_mode: service:secrets-service
  secrets-daprd:
    image: daprio/daprd:1.0.1
    command: [ "./daprd","-app-id","secrets","-app-port","80","-placement-host-address","placement:50006","-components-path","/components" ]
    volumes:
      - ./components:/components
    depends_on:
      - secrets-http
    network_mode: service:secrets-service
  client-service:
    image: ${DOCKER_USER}/php-client-service:latest
    build:
      args:
        SERVICE: client
      dockerfile: ../../examples/images/service.Dockerfile
      context: ../../examples/secrets
      target: production
    ports:
      - 8080:80
  client-http:
    image: ${DOCKER_USER}/php-client-http:latest
    build:
      args:
        SERVICE: client
      dockerfile: ../../examples/images/caddy.Dockerfile
      context: ../../examples/secrets
    depends_on:
      - client-service
    network_mode: service:client-service
  client-daprd:
    image: daprio/daprd:1.0.1
    command: [ "./daprd","-app-id","client","-app-port","80","-placement-host-address","placement:50006","-components-path","/components" ]
    depends_on:
      - client-http
    network_mode: service:client-service
