<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * Generated from protobuf message <code>dapr.proto.runtime.v1.ActiveActorsCount</code>
 */
interface ActiveActorsCountInterface
{
	/**
	 * Generated from protobuf field <code>string type = 1;</code>
	 * @return string
	 */
	public function getType();


	/**
	 * Generated from protobuf field <code>string type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setType($var);


	/**
	 * Generated from protobuf field <code>int32 count = 2;</code>
	 * @return int
	 */
	public function getCount();


	/**
	 * Generated from protobuf field <code>int32 count = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setCount($var);
}
