<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

interface AnyInterface
{
	public function getTypeUrl();


	public function setTypeUrl($value);


	public function getValue();


	public function setValue($value);


	public function is($proto);


	public function pack($value);


	public function unpack();
}
