<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * BulkStateItem is the response item for a bulk get operation.
 * Return values include the item key, data and etag.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.BulkStateItem</code>
 */
interface BulkStateItemInterface
{
	/**
	 * state item key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * state item key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);


	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);


	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 3;</code>
	 * @return string
	 */
	public function getEtag();


	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setEtag($var);


	/**
	 * The error that was returned from the state store in case of a failed get operation.
	 *
	 * Generated from protobuf field <code>string error = 4;</code>
	 * @return string
	 */
	public function getError();


	/**
	 * The error that was returned from the state store in case of a failed get operation.
	 *
	 * Generated from protobuf field <code>string error = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setError($var);


	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
