<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * DeleteStateRequest is the message to delete key-value states in the specific state store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.DeleteStateRequest</code>
 */
interface DeleteStateRequestInterface
{
	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @return string
	 */
	public function getStoreName();


	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName($var);


	/**
	 * The key of the desired state
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * The key of the desired state
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);


	/**
	 * The entity tag which represents the specific version of data.
	 * The exact ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.Etag etag = 3;</code>
	 * @return \Dapr\Proto\Common\V1\Etag|null
	 */
	public function getEtag();


	public function hasEtag();


	public function clearEtag();


	/**
	 * The entity tag which represents the specific version of data.
	 * The exact ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.Etag etag = 3;</code>
	 * @param \Dapr\Proto\Common\V1\Etag $var
	 * @return $this
	 */
	public function setEtag($var);


	/**
	 * State operation options which includes concurrency/
	 * consistency/retry_policy.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions options = 4;</code>
	 * @return \Dapr\Proto\Common\V1\StateOptions|null
	 */
	public function getOptions();


	public function hasOptions();


	public function clearOptions();


	/**
	 * State operation options which includes concurrency/
	 * consistency/retry_policy.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions options = 4;</code>
	 * @param \Dapr\Proto\Common\V1\StateOptions $var
	 * @return $this
	 */
	public function setOptions($var);


	/**
	 * The metadata which will be sent to state store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be sent to state store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
