<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * DeleteBulkStateRequest is the message to delete a list of key-value states from specific state store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.DeleteBulkStateRequest</code>
 */
interface DeleteBulkStateRequestInterface
{
	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @return string
	 */
	public function getStoreName();


	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName($var);


	/**
	 * The array of the state key values.
	 *
	 * Generated from protobuf field <code>repeated .dapr.proto.common.v1.StateItem states = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getStates();


	/**
	 * The array of the state key values.
	 *
	 * Generated from protobuf field <code>repeated .dapr.proto.common.v1.StateItem states = 2;</code>
	 * @param \Dapr\Proto\Common\V1\StateItem[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setStates($var);
}
