<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * ExecuteActorStateTransactionRequest is the message to execute multiple operations on a specified actor.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.ExecuteActorStateTransactionRequest</code>
 */
interface ExecuteActorStateTransactionRequestInterface
{
	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType();


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType($var);


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId();


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId($var);


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalActorStateOperation operations = 3;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getOperations();


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalActorStateOperation operations = 3;</code>
	 * @param \Dapr\Proto\Runtime\V1\TransactionalActorStateOperation[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setOperations($var);
}
