<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * ExecuteStateTransactionRequest is the message to execute multiple operations on a specified store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.ExecuteStateTransactionRequest</code>
 */
interface ExecuteStateTransactionRequestInterface
{
	/**
	 * Required. name of state store.
	 *
	 * Generated from protobuf field <code>string storeName = 1;</code>
	 * @return string
	 */
	public function getStoreName();


	/**
	 * Required. name of state store.
	 *
	 * Generated from protobuf field <code>string storeName = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName($var);


	/**
	 * Required. transactional operation list.
	 *
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalStateOperation operations = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getOperations();


	/**
	 * Required. transactional operation list.
	 *
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalStateOperation operations = 2;</code>
	 * @param \Dapr\Proto\Runtime\V1\TransactionalStateOperation[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setOperations($var);


	/**
	 * The metadata used for transactional operations.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata used for transactional operations.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
