<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetActorStateRequest is the message to get key-value states from specific actor.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetActorStateRequest</code>
 */
interface GetActorStateRequestInterface
{
	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType();


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType($var);


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId();


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId($var);


	/**
	 * Generated from protobuf field <code>string key = 3;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * Generated from protobuf field <code>string key = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);
}
