<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetBulkSecretResponse is the response message to convey the requested secrets.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetBulkSecretResponse</code>
 */
interface GetBulkSecretResponseInterface
{
	/**
	 * data hold the secret values. Some secret store, such as kubernetes secret
	 * store, can save multiple secrets for single secret key.
	 *
	 * Generated from protobuf field <code>map<string, .dapr.proto.runtime.v1.SecretResponse> data = 1;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getData();


	/**
	 * data hold the secret values. Some secret store, such as kubernetes secret
	 * store, can save multiple secrets for single secret key.
	 *
	 * Generated from protobuf field <code>map<string, .dapr.proto.runtime.v1.SecretResponse> data = 1;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setData($var);
}
