<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetBulkSecretRequest is the message to get the secrets from secret store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetBulkSecretRequest</code>
 */
interface GetBulkSecretRequestInterface
{
	/**
	 * The name of secret store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @return string
	 */
	public function getStoreName();


	/**
	 * The name of secret store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName($var);


	/**
	 * The metadata which will be sent to secret store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be sent to secret store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
