<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetBulkStateRequest is the message to get a list of key-value states from specific state store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetBulkStateRequest</code>
 */
interface GetBulkStateRequestInterface
{
	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @return string
	 */
	public function getStoreName();


	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName($var);


	/**
	 * The keys to get.
	 *
	 * Generated from protobuf field <code>repeated string keys = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getKeys();


	/**
	 * The keys to get.
	 *
	 * Generated from protobuf field <code>repeated string keys = 2;</code>
	 * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setKeys($var);


	/**
	 * The number of parallel operations executed on the state store for a get operation.
	 *
	 * Generated from protobuf field <code>int32 parallelism = 3;</code>
	 * @return int
	 */
	public function getParallelism();


	/**
	 * The number of parallel operations executed on the state store for a get operation.
	 *
	 * Generated from protobuf field <code>int32 parallelism = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setParallelism($var);


	/**
	 * The metadata which will be sent to state store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be sent to state store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
