<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetMetadataResponse is a message that is returned on GetMetadata rpc call
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetMetadataResponse</code>
 */
interface GetMetadataResponseInterface
{
	/**
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @return string
	 */
	public function getId();


	/**
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setId($var);


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.ActiveActorsCount active_actors_count = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getActiveActorsCount();


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.ActiveActorsCount active_actors_count = 2;</code>
	 * @param \Dapr\Proto\Runtime\V1\ActiveActorsCount[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setActiveActorsCount($var);


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.RegisteredComponents registered_components = 3;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getRegisteredComponents();


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.RegisteredComponents registered_components = 3;</code>
	 * @param \Dapr\Proto\Runtime\V1\RegisteredComponents[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setRegisteredComponents($var);


	/**
	 * Generated from protobuf field <code>map<string, string> extended_metadata = 4;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getExtendedMetadata();


	/**
	 * Generated from protobuf field <code>map<string, string> extended_metadata = 4;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setExtendedMetadata($var);
}
