<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetStateRequest is the message to get key-value states from specific state store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetStateRequest</code>
 */
interface GetStateRequestInterface
{
	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @return string
	 */
	public function getStoreName();


	/**
	 * The name of state store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName($var);


	/**
	 * The key of the desired state
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * The key of the desired state
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);


	/**
	 * The read consistency of the state store.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 3;</code>
	 * @return int
	 */
	public function getConsistency();


	/**
	 * The read consistency of the state store.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 3;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setConsistency($var);


	/**
	 * The metadata which will be sent to state store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be sent to state store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
