<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetSecretResponse is the response message to convey the requested secret.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetSecretResponse</code>
 */
interface GetSecretResponseInterface
{
	/**
	 * data is the secret value. Some secret store, such as kubernetes secret
	 * store, can save multiple secrets for single secret key.
	 *
	 * Generated from protobuf field <code>map<string, string> data = 1;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getData();


	/**
	 * data is the secret value. Some secret store, such as kubernetes secret
	 * store, can save multiple secrets for single secret key.
	 *
	 * Generated from protobuf field <code>map<string, string> data = 1;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setData($var);
}
