<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * GetStateResponse is the response conveying the state value and etag.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetStateResponse</code>
 */
interface GetStateResponseInterface
{
	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);


	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 2;</code>
	 * @return string
	 */
	public function getEtag();


	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setEtag($var);


	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
