<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * HTTPExtension includes HTTP verb and querystring
 * when Dapr runtime delivers HTTP content.
 *
 * For example, when callers calls http invoke api
 * POST http://localhost:3500/v1.0/invoke/<app_id>/method/<method>?query1=value1&query2=value2
 *
 * Dapr runtime will parse POST as a verb and extract querystring to quersytring map.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.HTTPExtension</code>
 */
interface HTTPExtensionInterface
{
	/**
	 * Required. HTTP verb.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension.Verb verb = 1;</code>
	 * @return int
	 */
	public function getVerb();


	/**
	 * Required. HTTP verb.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension.Verb verb = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setVerb($var);


	/**
	 * Optional. querystring represents an encoded HTTP url query string in the following format: name=value&name2=value2
	 *
	 * Generated from protobuf field <code>string querystring = 2;</code>
	 * @return string
	 */
	public function getQuerystring();


	/**
	 * Optional. querystring represents an encoded HTTP url query string in the following format: name=value&name2=value2
	 *
	 * Generated from protobuf field <code>string querystring = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setQuerystring($var);
}
