<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * InvokeActorResponse is the method that returns an actor invocation response.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeActorResponse</code>
 */
interface InvokeActorResponseInterface
{
	/**
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);
}
