<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * InvokeActorRequest is the message to call an actor.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeActorRequest</code>
 */
interface InvokeActorRequestInterface
{
	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType();


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType($var);


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId();


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId($var);


	/**
	 * Generated from protobuf field <code>string method = 3;</code>
	 * @return string
	 */
	public function getMethod();


	/**
	 * Generated from protobuf field <code>string method = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setMethod($var);


	/**
	 * Generated from protobuf field <code>bytes data = 4;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * Generated from protobuf field <code>bytes data = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);
}
