<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * InvokeBindingRequest is the message to send data to output bindings
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeBindingRequest</code>
 */
interface InvokeBindingRequestInterface
{
	/**
	 * The name of the output binding to invoke.
	 *
	 * Generated from protobuf field <code>string name = 1;</code>
	 * @return string
	 */
	public function getName();


	/**
	 * The name of the output binding to invoke.
	 *
	 * Generated from protobuf field <code>string name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var);


	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);


	/**
	 * The metadata passing to output binding components
	 *
	 * Common metadata property:
	 * - ttlInSeconds : the time to live in seconds for the message.
	 * If set in the binding definition will cause all messages to
	 * have a default time to live. The message ttl overrides any value
	 * in the binding definition.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata passing to output binding components
	 *
	 * Common metadata property:
	 * - ttlInSeconds : the time to live in seconds for the message.
	 * If set in the binding definition will cause all messages to
	 * have a default time to live. The message ttl overrides any value
	 * in the binding definition.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);


	/**
	 * The name of the operation type for the binding to invoke
	 *
	 * Generated from protobuf field <code>string operation = 4;</code>
	 * @return string
	 */
	public function getOperation();


	/**
	 * The name of the operation type for the binding to invoke
	 *
	 * Generated from protobuf field <code>string operation = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setOperation($var);
}
