<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * InvokeServiceRequest represents the request message for Service invocation.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeServiceRequest</code>
 */
interface InvokeServiceRequestInterface
{
	/**
	 * Required. Callee's app id.
	 *
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @return string
	 */
	public function getId();


	/**
	 * Required. Callee's app id.
	 *
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setId($var);


	/**
	 * Required. message which will be delivered to callee.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
	 * @return \Dapr\Proto\Common\V1\InvokeRequest|null
	 */
	public function getMessage();


	public function hasMessage();


	public function clearMessage();


	/**
	 * Required. message which will be delivered to callee.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
	 * @param \Dapr\Proto\Common\V1\InvokeRequest $var
	 * @return $this
	 */
	public function setMessage($var);
}
