<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * InvokeBindingResponse is the message returned from an output binding invocation
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeBindingResponse</code>
 */
interface InvokeBindingResponseInterface
{
	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);


	/**
	 * The metadata returned from an external system
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata returned from an external system
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
