<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * InvokeResponse is the response message inclduing data and its content type
 * from app callback.
 * This message is used in InvokeService of Dapr gRPC Service and OnInvoke
 * of AppCallback gRPC service.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.InvokeResponse</code>
 */
interface InvokeResponseInterface
{
	/**
	 * Required. The content body of InvokeService response.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
	 * @return \Google\Protobuf\Any|null
	 */
	public function getData();


	public function hasData();


	public function clearData();


	/**
	 * Required. The content body of InvokeService response.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
	 * @param \Google\Protobuf\Any $var
	 * @return $this
	 */
	public function setData($var);


	/**
	 * Required. The type of data content.
	 *
	 * Generated from protobuf field <code>string content_type = 2;</code>
	 * @return string
	 */
	public function getContentType();


	/**
	 * Required. The type of data content.
	 *
	 * Generated from protobuf field <code>string content_type = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setContentType($var);
}
