<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * PublishEventRequest is the message to publish event data to pubsub topic
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.PublishEventRequest</code>
 */
interface PublishEventRequestInterface
{
	/**
	 * The name of the pubsub component
	 *
	 * Generated from protobuf field <code>string pubsub_name = 1;</code>
	 * @return string
	 */
	public function getPubsubName();


	/**
	 * The name of the pubsub component
	 *
	 * Generated from protobuf field <code>string pubsub_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPubsubName($var);


	/**
	 * The pubsub topic
	 *
	 * Generated from protobuf field <code>string topic = 2;</code>
	 * @return string
	 */
	public function getTopic();


	/**
	 * The pubsub topic
	 *
	 * Generated from protobuf field <code>string topic = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setTopic($var);


	/**
	 * The data which will be published to topic.
	 *
	 * Generated from protobuf field <code>bytes data = 3;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * The data which will be published to topic.
	 *
	 * Generated from protobuf field <code>bytes data = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);


	/**
	 * The content type for the data (optional).
	 *
	 * Generated from protobuf field <code>string data_content_type = 4;</code>
	 * @return string
	 */
	public function getDataContentType();


	/**
	 * The content type for the data (optional).
	 *
	 * Generated from protobuf field <code>string data_content_type = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setDataContentType($var);


	/**
	 * The metadata passing to pub components
	 *
	 * metadata property:
	 * - key : the key of the message.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata passing to pub components
	 *
	 * metadata property:
	 * - key : the key of the message.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);
}
