<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * RegisterActorReminderRequest is the message to register a reminder for an actor of a given type and id.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.RegisterActorReminderRequest</code>
 */
interface RegisterActorReminderRequestInterface
{
	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType();


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType($var);


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId();


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId($var);


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @return string
	 */
	public function getName();


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var);


	/**
	 * Generated from protobuf field <code>string due_time = 4;</code>
	 * @return string
	 */
	public function getDueTime();


	/**
	 * Generated from protobuf field <code>string due_time = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setDueTime($var);


	/**
	 * Generated from protobuf field <code>string period = 5;</code>
	 * @return string
	 */
	public function getPeriod();


	/**
	 * Generated from protobuf field <code>string period = 5;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPeriod($var);


	/**
	 * Generated from protobuf field <code>bytes data = 6;</code>
	 * @return string
	 */
	public function getData();


	/**
	 * Generated from protobuf field <code>bytes data = 6;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData($var);
}
