<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

interface RepeatedFieldInterface
{
	public function append($newval);


	public function offsetExists($index);


	public function offsetGet($index);


	public function offsetSet($index, $newval);


	public function offsetUnset($index);


	public function count();


	public function getIterator();
}
