<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * SecretResponse is a map of decrypted string/string values
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.SecretResponse</code>
 */
interface SecretResponseInterface
{
	/**
	 * Generated from protobuf field <code>map<string, string> secrets = 1;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getSecrets();


	/**
	 * Generated from protobuf field <code>map<string, string> secrets = 1;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setSecrets($var);
}
