<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * Generated from protobuf message <code>dapr.proto.runtime.v1.SetMetadataRequest</code>
 */
interface SetMetadataRequestInterface
{
	/**
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);


	/**
	 * Generated from protobuf field <code>string value = 2;</code>
	 * @return string
	 */
	public function getValue();


	/**
	 * Generated from protobuf field <code>string value = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setValue($var);
}
