<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * StateOptions configures concurrency and consistency for state operations
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.StateOptions</code>
 */
interface StateOptionsInterface
{
	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConcurrency concurrency = 1;</code>
	 * @return int
	 */
	public function getConcurrency();


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConcurrency concurrency = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setConcurrency($var);


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 2;</code>
	 * @return int
	 */
	public function getConsistency();


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setConsistency($var);
}
