<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * Enum describing the supported consistency for state.
 *
 * Protobuf type <code>dapr.proto.common.v1.StateOptions.StateConsistency</code>
 */
interface StateConsistencyInterface
{
	/** Generated from protobuf enum <code>CONSISTENCY_UNSPECIFIED = 0;</code> */
	public const CONSISTENCY_UNSPECIFIED = 0;

	/** Generated from protobuf enum <code>CONSISTENCY_EVENTUAL = 1;</code> */
	public const CONSISTENCY_EVENTUAL = 1;

	/** Generated from protobuf enum <code>CONSISTENCY_STRONG = 2;</code> */
	public const CONSISTENCY_STRONG = 2;

	public static function name($value);


	public static function value($name);
}
