<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * StateItem represents state key, value, and additional options to save state.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.StateItem</code>
 */
interface StateItemInterface
{
	/**
	 * Required. The state key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * Required. The state key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);


	/**
	 * Required. The state data for key
	 *
	 * Generated from protobuf field <code>bytes value = 2;</code>
	 * @return string
	 */
	public function getValue();


	/**
	 * Required. The state data for key
	 *
	 * Generated from protobuf field <code>bytes value = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setValue($var);


	/**
	 * The entity tag which represents the specific version of data.
	 * The exact ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.Etag etag = 3;</code>
	 * @return \Dapr\Proto\Common\V1\Etag|null
	 */
	public function getEtag();


	public function hasEtag();


	public function clearEtag();


	/**
	 * The entity tag which represents the specific version of data.
	 * The exact ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.Etag etag = 3;</code>
	 * @param \Dapr\Proto\Common\V1\Etag $var
	 * @return $this
	 */
	public function setEtag($var);


	/**
	 * The metadata which will be passed to state store component.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata();


	/**
	 * The metadata which will be passed to state store component.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata($var);


	/**
	 * Options for concurrency and consistency to save the state.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions options = 5;</code>
	 * @return \Dapr\Proto\Common\V1\StateOptions|null
	 */
	public function getOptions();


	public function hasOptions();


	public function clearOptions();


	/**
	 * Options for concurrency and consistency to save the state.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions options = 5;</code>
	 * @param \Dapr\Proto\Common\V1\StateOptions $var
	 * @return $this
	 */
	public function setOptions($var);
}
