<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * TransactionalStateOperation is the message to execute a specified operation with a key-value pair.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.TransactionalStateOperation</code>
 */
interface TransactionalStateOperationInterface
{
	/**
	 * The type of operation to be executed
	 *
	 * Generated from protobuf field <code>string operationType = 1;</code>
	 * @return string
	 */
	public function getOperationType();


	/**
	 * The type of operation to be executed
	 *
	 * Generated from protobuf field <code>string operationType = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setOperationType($var);


	/**
	 * State values to be operated on
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateItem request = 2;</code>
	 * @return \Dapr\Proto\Common\V1\StateItem|null
	 */
	public function getRequest();


	public function hasRequest();


	public function clearRequest();


	/**
	 * State values to be operated on
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateItem request = 2;</code>
	 * @param \Dapr\Proto\Common\V1\StateItem $var
	 * @return $this
	 */
	public function setRequest($var);
}
