<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * TransactionalAcorStateOperation is the message to execute a specified operation with a key-value pair.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.TransactionalActorStateOperation</code>
 */
interface TransactionalActorStateOperationInterface
{
	/**
	 * Generated from protobuf field <code>string operationType = 1;</code>
	 * @return string
	 */
	public function getOperationType();


	/**
	 * Generated from protobuf field <code>string operationType = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setOperationType($var);


	/**
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @return string
	 */
	public function getKey();


	/**
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey($var);


	/**
	 * Generated from protobuf field <code>.google.protobuf.Any value = 3;</code>
	 * @return \Google\Protobuf\Any|null
	 */
	public function getValue();


	public function hasValue();


	public function clearValue();


	/**
	 * Generated from protobuf field <code>.google.protobuf.Any value = 3;</code>
	 * @param \Google\Protobuf\Any $var
	 * @return $this
	 */
	public function setValue($var);
}
