<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Client\Interfaces\V1;

/**
 * UnregisterActorTimerRequest is the message to unregister an actor timer
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.UnregisterActorTimerRequest</code>
 */
interface UnregisterActorTimerRequestInterface
{
	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType();


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType($var);


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId();


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId($var);


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @return string
	 */
	public function getName();


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName($var);
}
