<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

namespace Dapr\Proto\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Etag represents a state item version
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.Etag</code>
 */
class Etag extends \Google\Protobuf\Internal\Message
{
    /**
     * value sets the etag value
     *
     * Generated from protobuf field <code>string value = 1;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *           value sets the etag value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dapr\Proto\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * value sets the etag value
     *
     * Generated from protobuf field <code>string value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * value sets the etag value
     *
     * Generated from protobuf field <code>string value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

