<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Common\V1;

/**
 * Type of HTTP 1.1 Methods
 * RFC 7231: https://tools.ietf.org/html/rfc7231#page-24
 *
 * Protobuf type <code>dapr.proto.common.v1.HTTPExtension.Verb</code>
 */
class Verb
{
	/** Generated from protobuf enum <code>NONE = 0;</code> */
	public const NONE = 0;

	/** Generated from protobuf enum <code>GET = 1;</code> */
	public const GET = 1;

	/** Generated from protobuf enum <code>HEAD = 2;</code> */
	public const HEAD = 2;

	/** Generated from protobuf enum <code>POST = 3;</code> */
	public const POST = 3;

	/** Generated from protobuf enum <code>PUT = 4;</code> */
	public const PUT = 4;

	/** Generated from protobuf enum <code>DELETE = 5;</code> */
	public const DELETE = 5;

	/** Generated from protobuf enum <code>CONNECT = 6;</code> */
	public const CONNECT = 6;

	/** Generated from protobuf enum <code>OPTIONS = 7;</code> */
	public const OPTIONS = 7;

	/** Generated from protobuf enum <code>TRACE = 8;</code> */
	public const TRACE = 8;

	private static $valueToName = ['NONE', 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'CONNECT', 'OPTIONS', 'TRACE'];


	public static function name($value)
	{
		if (!isset(self::$valueToName[$value])) {
		    throw new \UnexpectedValueException(sprintf(
		            'Enum %s has no name defined for value %s', __CLASS__, $value));
		}
		return self::$valueToName[$value];
	}


	public static function value($name)
	{
		$const = __CLASS__ . '::' . strtoupper($name);
		if (!defined($const)) {
		    throw new \UnexpectedValueException(sprintf(
		            'Enum %s has no value defined for name %s', __CLASS__, $name));
		}
		return constant($const);
	}
}
