<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

namespace Dapr\Proto\Common\V1;

if (false) {
    /**
     * This class is deprecated. Use Dapr\Proto\Common\V1\HTTPExtension\Verb instead.
     * @deprecated
     */
    class HTTPExtension_Verb {}
}
class_exists(HTTPExtension\Verb::class);
@trigger_error('Dapr\Proto\Common\V1\HTTPExtension_Verb is deprecated and will be removed in the next major release. Use Dapr\Proto\Common\V1\HTTPExtension\Verb instead', E_USER_DEPRECATED);

