<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

namespace Dapr\Proto\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * InvokeRequest is the message to invoke a method with the data.
 * This message is used in InvokeService of Dapr gRPC Service and OnInvoke
 * of AppCallback gRPC service.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.InvokeRequest</code>
 */
class InvokeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. method is a method name which will be invoked by caller.
     *
     * Generated from protobuf field <code>string method = 1;</code>
     */
    protected $method = '';
    /**
     * Required. Bytes value or Protobuf message which caller sent.
     * Dapr treats Any.value as bytes type if Any.type_url is unset.
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 2;</code>
     */
    protected $data = null;
    /**
     * The type of data content.
     * This field is required if data delivers http request body
     * Otherwise, this is optional.
     *
     * Generated from protobuf field <code>string content_type = 3;</code>
     */
    protected $content_type = '';
    /**
     * HTTP specific fields if request conveys http-compatible request.
     * This field is required for http-compatible request. Otherwise,
     * this field is optional.
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension http_extension = 4;</code>
     */
    protected $http_extension = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $method
     *           Required. method is a method name which will be invoked by caller.
     *     @type \Google\Protobuf\Any $data
     *           Required. Bytes value or Protobuf message which caller sent.
     *           Dapr treats Any.value as bytes type if Any.type_url is unset.
     *     @type string $content_type
     *           The type of data content.
     *           This field is required if data delivers http request body
     *           Otherwise, this is optional.
     *     @type \Dapr\Proto\Common\V1\HTTPExtension $http_extension
     *           HTTP specific fields if request conveys http-compatible request.
     *           This field is required for http-compatible request. Otherwise,
     *           this field is optional.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dapr\Proto\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. method is a method name which will be invoked by caller.
     *
     * Generated from protobuf field <code>string method = 1;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Required. method is a method name which will be invoked by caller.
     *
     * Generated from protobuf field <code>string method = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Required. Bytes value or Protobuf message which caller sent.
     * Dapr treats Any.value as bytes type if Any.type_url is unset.
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 2;</code>
     * @return \Google\Protobuf\Any
     */
    public function getData()
    {
        return isset($this->data) ? $this->data : null;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Required. Bytes value or Protobuf message which caller sent.
     * Dapr treats Any.value as bytes type if Any.type_url is unset.
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 2;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->data = $var;

        return $this;
    }

    /**
     * The type of data content.
     * This field is required if data delivers http request body
     * Otherwise, this is optional.
     *
     * Generated from protobuf field <code>string content_type = 3;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * The type of data content.
     * This field is required if data delivers http request body
     * Otherwise, this is optional.
     *
     * Generated from protobuf field <code>string content_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

    /**
     * HTTP specific fields if request conveys http-compatible request.
     * This field is required for http-compatible request. Otherwise,
     * this field is optional.
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension http_extension = 4;</code>
     * @return \Dapr\Proto\Common\V1\HTTPExtension
     */
    public function getHttpExtension()
    {
        return isset($this->http_extension) ? $this->http_extension : null;
    }

    public function hasHttpExtension()
    {
        return isset($this->http_extension);
    }

    public function clearHttpExtension()
    {
        unset($this->http_extension);
    }

    /**
     * HTTP specific fields if request conveys http-compatible request.
     * This field is required for http-compatible request. Otherwise,
     * this field is optional.
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension http_extension = 4;</code>
     * @param \Dapr\Proto\Common\V1\HTTPExtension $var
     * @return $this
     */
    public function setHttpExtension($var)
    {
        GPBUtil::checkMessage($var, \Dapr\Proto\Common\V1\HTTPExtension::class);
        $this->http_extension = $var;

        return $this;
    }

}

