<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Common\V1;

/**
 * InvokeResponse is the response message inclduing data and its content type
 * from app callback.
 * This message is used in InvokeService of Dapr gRPC Service and OnInvoke
 * of AppCallback gRPC service.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.InvokeResponse</code>
 */
class InvokeResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * Required. The content body of InvokeService response.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
	 */
	protected $data;

	/**
	 * Required. The type of data content.
	 *
	 * Generated from protobuf field <code>string content_type = 2;</code>
	 */
	protected $content_type = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type \Google\Protobuf\Any $data
	 *           Required. The content body of InvokeService response.
	 *     @type string $content_type
	 *           Required. The type of data content.
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Common\V1\Common::initOnce();
		parent::__construct($data);
	}


	/**
	 * Required. The content body of InvokeService response.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
	 * @return \Google\Protobuf\Any|null
	 */
	public function getData(): \Google\Protobuf\Any|null
	{
		return isset($this->data) ? $this->data : null;
	}


	public function hasData(): bool
	{
		return isset($this->data);
	}


	public function clearData(): void
	{
		unset($this->data);
	}


	/**
	 * Required. The content body of InvokeService response.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
	 * @param \Google\Protobuf\Any $var
	 * @return $this
	 */
	public function setData(\Google\Protobuf\Any $var): InvokeResponse
	{
		\Google\Protobuf\Internal\GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
		$this->data = $var;

		return $this;
	}


	/**
	 * Required. The type of data content.
	 *
	 * Generated from protobuf field <code>string content_type = 2;</code>
	 * @return string
	 */
	public function getContentType(): string
	{
		return $this->content_type;
	}


	/**
	 * Required. The type of data content.
	 *
	 * Generated from protobuf field <code>string content_type = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setContentType(string $var): InvokeResponse
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->content_type = $var;

		return $this;
	}
}
