<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Common\V1;

/**
 * InvokeRequest is the message to invoke a method with the data.
 * This message is used in InvokeService of Dapr gRPC Service and OnInvoke
 * of AppCallback gRPC service.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.InvokeRequest</code>
 */
class InvokeRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Required. method is a method name which will be invoked by caller.
	 *
	 * Generated from protobuf field <code>string method = 1;</code>
	 */
	protected $method = '';

	/**
	 * Required. Bytes value or Protobuf message which caller sent.
	 * Dapr treats Any.value as bytes type if Any.type_url is unset.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 2;</code>
	 */
	protected $data;

	/**
	 * The type of data content.
	 * This field is required if data delivers http request body
	 * Otherwise, this is optional.
	 *
	 * Generated from protobuf field <code>string content_type = 3;</code>
	 */
	protected $content_type = '';

	/**
	 * HTTP specific fields if request conveys http-compatible request.
	 * This field is required for http-compatible request. Otherwise,
	 * this field is optional.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension http_extension = 4;</code>
	 */
	protected $http_extension;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $method
	 *           Required. method is a method name which will be invoked by caller.
	 *     @type \Google\Protobuf\Any $data
	 *           Required. Bytes value or Protobuf message which caller sent.
	 *           Dapr treats Any.value as bytes type if Any.type_url is unset.
	 *     @type string $content_type
	 *           The type of data content.
	 *           This field is required if data delivers http request body
	 *           Otherwise, this is optional.
	 *     @type \Dapr\Proto\Common\V1\HTTPExtension $http_extension
	 *           HTTP specific fields if request conveys http-compatible request.
	 *           This field is required for http-compatible request. Otherwise,
	 *           this field is optional.
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Common\V1\Common::initOnce();
		parent::__construct($data);
	}


	/**
	 * Required. method is a method name which will be invoked by caller.
	 *
	 * Generated from protobuf field <code>string method = 1;</code>
	 * @return string
	 */
	public function getMethod(): string
	{
		return $this->method;
	}


	/**
	 * Required. method is a method name which will be invoked by caller.
	 *
	 * Generated from protobuf field <code>string method = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setMethod(string $var): InvokeRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->method = $var;

		return $this;
	}


	/**
	 * Required. Bytes value or Protobuf message which caller sent.
	 * Dapr treats Any.value as bytes type if Any.type_url is unset.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 2;</code>
	 * @return \Google\Protobuf\Any|null
	 */
	public function getData(): \Google\Protobuf\Any|null
	{
		return isset($this->data) ? $this->data : null;
	}


	public function hasData(): bool
	{
		return isset($this->data);
	}


	public function clearData(): void
	{
		unset($this->data);
	}


	/**
	 * Required. Bytes value or Protobuf message which caller sent.
	 * Dapr treats Any.value as bytes type if Any.type_url is unset.
	 *
	 * Generated from protobuf field <code>.google.protobuf.Any data = 2;</code>
	 * @param \Google\Protobuf\Any $var
	 * @return $this
	 */
	public function setData(\Google\Protobuf\Any $var): InvokeRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
		$this->data = $var;

		return $this;
	}


	/**
	 * The type of data content.
	 * This field is required if data delivers http request body
	 * Otherwise, this is optional.
	 *
	 * Generated from protobuf field <code>string content_type = 3;</code>
	 * @return string
	 */
	public function getContentType(): string
	{
		return $this->content_type;
	}


	/**
	 * The type of data content.
	 * This field is required if data delivers http request body
	 * Otherwise, this is optional.
	 *
	 * Generated from protobuf field <code>string content_type = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setContentType(string $var): InvokeRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->content_type = $var;

		return $this;
	}


	/**
	 * HTTP specific fields if request conveys http-compatible request.
	 * This field is required for http-compatible request. Otherwise,
	 * this field is optional.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension http_extension = 4;</code>
	 * @return \Dapr\Proto\Common\V1\HTTPExtension|null
	 */
	public function getHttpExtension(): HTTPExtension|null
	{
		return isset($this->http_extension) ? $this->http_extension : null;
	}


	public function hasHttpExtension(): bool
	{
		return isset($this->http_extension);
	}


	public function clearHttpExtension(): void
	{
		unset($this->http_extension);
	}


	/**
	 * HTTP specific fields if request conveys http-compatible request.
	 * This field is required for http-compatible request. Otherwise,
	 * this field is optional.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.HTTPExtension http_extension = 4;</code>
	 * @param \Dapr\Proto\Common\V1\HTTPExtension $var
	 * @return $this
	 */
	public function setHttpExtension(HTTPExtension $var): InvokeRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkMessage($var, \Dapr\Proto\Common\V1\HTTPExtension::class);
		$this->http_extension = $var;

		return $this;
	}
}
