<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

namespace Dapr\Proto\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * InvokeResponse is the response message inclduing data and its content type
 * from app callback.
 * This message is used in InvokeService of Dapr gRPC Service and OnInvoke
 * of AppCallback gRPC service.
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.InvokeResponse</code>
 */
class InvokeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The content body of InvokeService response.
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
     */
    protected $data = null;
    /**
     * Required. The type of data content.
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     */
    protected $content_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any $data
     *           Required. The content body of InvokeService response.
     *     @type string $content_type
     *           Required. The type of data content.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dapr\Proto\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The content body of InvokeService response.
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
     * @return \Google\Protobuf\Any
     */
    public function getData()
    {
        return isset($this->data) ? $this->data : null;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Required. The content body of InvokeService response.
     *
     * Generated from protobuf field <code>.google.protobuf.Any data = 1;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Required. The type of data content.
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Required. The type of data content.
     *
     * Generated from protobuf field <code>string content_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

}

