<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

namespace Dapr\Proto\Common\V1;

if (false) {
    /**
     * This class is deprecated. Use Dapr\Proto\Common\V1\StateOptions\StateConcurrency instead.
     * @deprecated
     */
    class StateOptions_StateConcurrency {}
}
class_exists(StateOptions\StateConcurrency::class);
@trigger_error('Dapr\Proto\Common\V1\StateOptions_StateConcurrency is deprecated and will be removed in the next major release. Use Dapr\Proto\Common\V1\StateOptions\StateConcurrency instead', E_USER_DEPRECATED);

