<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Common\V1;

/**
 * Enum describing the supported concurrency for state.
 *
 * Protobuf type <code>dapr.proto.common.v1.StateOptions.StateConcurrency</code>
 */
class StateConcurrency
{
	/** Generated from protobuf enum <code>CONCURRENCY_UNSPECIFIED = 0;</code> */
	public const CONCURRENCY_UNSPECIFIED = 0;

	/** Generated from protobuf enum <code>CONCURRENCY_FIRST_WRITE = 1;</code> */
	public const CONCURRENCY_FIRST_WRITE = 1;

	/** Generated from protobuf enum <code>CONCURRENCY_LAST_WRITE = 2;</code> */
	public const CONCURRENCY_LAST_WRITE = 2;

	private static $valueToName = ['CONCURRENCY_UNSPECIFIED', 'CONCURRENCY_FIRST_WRITE', 'CONCURRENCY_LAST_WRITE'];


	public static function name($value)
	{
		if (!isset(self::$valueToName[$value])) {
		    throw new \UnexpectedValueException(sprintf(
		            'Enum %s has no name defined for value %s', __CLASS__, $value));
		}
		return self::$valueToName[$value];
	}


	public static function value($name)
	{
		$const = __CLASS__ . '::' . strtoupper($name);
		if (!defined($const)) {
		    throw new \UnexpectedValueException(sprintf(
		            'Enum %s has no value defined for name %s', __CLASS__, $name));
		}
		return constant($const);
	}
}
