<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Common\V1;

/**
 * StateOptions configures concurrency and consistency for state operations
 *
 * Generated from protobuf message <code>dapr.proto.common.v1.StateOptions</code>
 */
class StateOptions extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConcurrency concurrency = 1;</code> */
	protected $concurrency = 0;

	/** Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 2;</code> */
	protected $consistency = 0;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type int $concurrency
	 *     @type int $consistency
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Common\V1\Common::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConcurrency concurrency = 1;</code>
	 * @return int
	 */
	public function getConcurrency(): int
	{
		return $this->concurrency;
	}


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConcurrency concurrency = 1;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setConcurrency(int $var): StateOptions
	{
		\Google\Protobuf\Internal\GPBUtil::checkEnum($var, \Dapr\Proto\Common\V1\StateOptions\StateConcurrency::class);
		$this->concurrency = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 2;</code>
	 * @return int
	 */
	public function getConsistency(): int
	{
		return $this->consistency;
	}


	/**
	 * Generated from protobuf field <code>.dapr.proto.common.v1.StateOptions.StateConsistency consistency = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setConsistency(int $var): StateOptions
	{
		\Google\Protobuf\Internal\GPBUtil::checkEnum($var, \Dapr\Proto\Common\V1\StateOptions\StateConsistency::class);
		$this->consistency = $var;

		return $this;
	}
}
