<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

namespace Dapr\Proto\Common\V1;

if (false) {
    /**
     * This class is deprecated. Use Dapr\Proto\Common\V1\StateOptions\StateConsistency instead.
     * @deprecated
     */
    class StateOptions_StateConsistency {}
}
class_exists(StateOptions\StateConsistency::class);
@trigger_error('Dapr\Proto\Common\V1\StateOptions_StateConsistency is deprecated and will be removed in the next major release. Use Dapr\Proto\Common\V1\StateOptions\StateConsistency instead', E_USER_DEPRECATED);

