<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * Generated from protobuf message <code>dapr.proto.runtime.v1.ActiveActorsCount</code>
 */
class ActiveActorsCount extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string type = 1;</code> */
	protected $type = '';

	/** Generated from protobuf field <code>int32 count = 2;</code> */
	protected $count = 0;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $type
	 *     @type int $count
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string type = 1;</code>
	 * @return string
	 */
	public function getType(): string
	{
		return $this->type;
	}


	/**
	 * Generated from protobuf field <code>string type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setType(string $var): ActiveActorsCount
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->type = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>int32 count = 2;</code>
	 * @return int
	 */
	public function getCount(): int
	{
		return $this->count;
	}


	/**
	 * Generated from protobuf field <code>int32 count = 2;</code>
	 * @param int $var
	 * @return $this
	 */
	public function setCount(int $var): ActiveActorsCount
	{
		\Google\Protobuf\Internal\GPBUtil::checkInt32($var);
		$this->count = $var;

		return $this;
	}
}
