<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * BulkStateItem is the response item for a bulk get operation.
 * Return values include the item key, data and etag.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.BulkStateItem</code>
 */
class BulkStateItem extends \Google\Protobuf\Internal\Message
{
	/**
	 * state item key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 */
	protected $key = '';

	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 */
	protected $data = '';

	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 3;</code>
	 */
	protected $etag = '';

	/**
	 * The error that was returned from the state store in case of a failed get operation.
	 *
	 * Generated from protobuf field <code>string error = 4;</code>
	 */
	protected $error = '';

	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 */
	private $metadata;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $key
	 *           state item key
	 *     @type string $data
	 *           The byte array data
	 *     @type string $etag
	 *           The entity tag which represents the specific version of data.
	 *           ETag format is defined by the corresponding data store.
	 *     @type string $error
	 *           The error that was returned from the state store in case of a failed get operation.
	 *     @type array|\Google\Protobuf\Internal\MapField $metadata
	 *           The metadata which will be sent to app.
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * state item key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @return string
	 */
	public function getKey(): string
	{
		return $this->key;
	}


	/**
	 * state item key
	 *
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey(string $var): BulkStateItem
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->key = $var;

		return $this;
	}


	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 * @return string
	 */
	public function getData(): string
	{
		return $this->data;
	}


	/**
	 * The byte array data
	 *
	 * Generated from protobuf field <code>bytes data = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData(string $var): BulkStateItem
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, False);
		$this->data = $var;

		return $this;
	}


	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 3;</code>
	 * @return string
	 */
	public function getEtag(): string
	{
		return $this->etag;
	}


	/**
	 * The entity tag which represents the specific version of data.
	 * ETag format is defined by the corresponding data store.
	 *
	 * Generated from protobuf field <code>string etag = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setEtag(string $var): BulkStateItem
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->etag = $var;

		return $this;
	}


	/**
	 * The error that was returned from the state store in case of a failed get operation.
	 *
	 * Generated from protobuf field <code>string error = 4;</code>
	 * @return string
	 */
	public function getError(): string
	{
		return $this->error;
	}


	/**
	 * The error that was returned from the state store in case of a failed get operation.
	 *
	 * Generated from protobuf field <code>string error = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setError(string $var): BulkStateItem
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->error = $var;

		return $this;
	}


	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata(): \Google\Protobuf\Internal\MapField
	{
		return $this->metadata;
	}


	/**
	 * The metadata which will be sent to app.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata(array|\Google\Protobuf\Internal\MapField $var): BulkStateItem
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
		$this->metadata = $arr;

		return $this;
	}
}
