<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime/v1/dapr.proto

namespace Dapr\Proto\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * BulkStateItem is the response item for a bulk get operation.
 * Return values include the item key, data and etag.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.BulkStateItem</code>
 */
class BulkStateItem extends \Google\Protobuf\Internal\Message
{
    /**
     * state item key
     *
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * The byte array data
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';
    /**
     * The entity tag which represents the specific version of data.
     * ETag format is defined by the corresponding data store.
     *
     * Generated from protobuf field <code>string etag = 3;</code>
     */
    protected $etag = '';
    /**
     * The error that was returned from the state store in case of a failed get operation.
     *
     * Generated from protobuf field <code>string error = 4;</code>
     */
    protected $error = '';
    /**
     * The metadata which will be sent to app.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *           state item key
     *     @type string $data
     *           The byte array data
     *     @type string $etag
     *           The entity tag which represents the specific version of data.
     *           ETag format is defined by the corresponding data store.
     *     @type string $error
     *           The error that was returned from the state store in case of a failed get operation.
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *           The metadata which will be sent to app.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Runtime\V1\Dapr::initOnce();
        parent::__construct($data);
    }

    /**
     * state item key
     *
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * state item key
     *
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * The byte array data
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * The byte array data
     *
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * The entity tag which represents the specific version of data.
     * ETag format is defined by the corresponding data store.
     *
     * Generated from protobuf field <code>string etag = 3;</code>
     * @return string
     */
    public function getEtag()
    {
        return $this->etag;
    }

    /**
     * The entity tag which represents the specific version of data.
     * ETag format is defined by the corresponding data store.
     *
     * Generated from protobuf field <code>string etag = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEtag($var)
    {
        GPBUtil::checkString($var, True);
        $this->etag = $var;

        return $this;
    }

    /**
     * The error that was returned from the state store in case of a failed get operation.
     *
     * Generated from protobuf field <code>string error = 4;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * The error that was returned from the state store in case of a failed get operation.
     *
     * Generated from protobuf field <code>string error = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * The metadata which will be sent to app.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * The metadata which will be sent to app.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

