<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime/v1/dapr.proto

namespace Dapr\Proto\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ExecuteActorStateTransactionRequest is the message to execute multiple operations on a specified actor.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.ExecuteActorStateTransactionRequest</code>
 */
class ExecuteActorStateTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string actor_type = 1;</code>
     */
    protected $actor_type = '';
    /**
     * Generated from protobuf field <code>string actor_id = 2;</code>
     */
    protected $actor_id = '';
    /**
     * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalActorStateOperation operations = 3;</code>
     */
    private $operations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $actor_type
     *     @type string $actor_id
     *     @type \Dapr\Proto\Runtime\V1\TransactionalActorStateOperation[]|\Google\Protobuf\Internal\RepeatedField $operations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Runtime\V1\Dapr::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string actor_type = 1;</code>
     * @return string
     */
    public function getActorType()
    {
        return $this->actor_type;
    }

    /**
     * Generated from protobuf field <code>string actor_type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setActorType($var)
    {
        GPBUtil::checkString($var, True);
        $this->actor_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string actor_id = 2;</code>
     * @return string
     */
    public function getActorId()
    {
        return $this->actor_id;
    }

    /**
     * Generated from protobuf field <code>string actor_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setActorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->actor_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalActorStateOperation operations = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperations()
    {
        return $this->operations;
    }

    /**
     * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.TransactionalActorStateOperation operations = 3;</code>
     * @param \Dapr\Proto\Runtime\V1\TransactionalActorStateOperation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dapr\Proto\Runtime\V1\TransactionalActorStateOperation::class);
        $this->operations = $arr;

        return $this;
    }

}

