<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime/v1/dapr.proto

namespace Dapr\Proto\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * GetBulkStateRequest is the message to get a list of key-value states from specific state store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetBulkStateRequest</code>
 */
class GetBulkStateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of state store.
     *
     * Generated from protobuf field <code>string store_name = 1;</code>
     */
    protected $store_name = '';
    /**
     * The keys to get.
     *
     * Generated from protobuf field <code>repeated string keys = 2;</code>
     */
    private $keys;
    /**
     * The number of parallel operations executed on the state store for a get operation.
     *
     * Generated from protobuf field <code>int32 parallelism = 3;</code>
     */
    protected $parallelism = 0;
    /**
     * The metadata which will be sent to state store components.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
     */
    private $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $store_name
     *           The name of state store.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $keys
     *           The keys to get.
     *     @type int $parallelism
     *           The number of parallel operations executed on the state store for a get operation.
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *           The metadata which will be sent to state store components.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Runtime\V1\Dapr::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of state store.
     *
     * Generated from protobuf field <code>string store_name = 1;</code>
     * @return string
     */
    public function getStoreName()
    {
        return $this->store_name;
    }

    /**
     * The name of state store.
     *
     * Generated from protobuf field <code>string store_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStoreName($var)
    {
        GPBUtil::checkString($var, True);
        $this->store_name = $var;

        return $this;
    }

    /**
     * The keys to get.
     *
     * Generated from protobuf field <code>repeated string keys = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * The keys to get.
     *
     * Generated from protobuf field <code>repeated string keys = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

    /**
     * The number of parallel operations executed on the state store for a get operation.
     *
     * Generated from protobuf field <code>int32 parallelism = 3;</code>
     * @return int
     */
    public function getParallelism()
    {
        return $this->parallelism;
    }

    /**
     * The number of parallel operations executed on the state store for a get operation.
     *
     * Generated from protobuf field <code>int32 parallelism = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setParallelism($var)
    {
        GPBUtil::checkInt32($var);
        $this->parallelism = $var;

        return $this;
    }

    /**
     * The metadata which will be sent to state store components.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * The metadata which will be sent to state store components.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

}

