<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * GetMetadataResponse is a message that is returned on GetMetadata rpc call
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetMetadataResponse</code>
 */
class GetMetadataResponse extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string id = 1;</code> */
	protected $id = '';

	/** Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.ActiveActorsCount active_actors_count = 2;</code> */
	private $active_actors_count;

	/** Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.RegisteredComponents registered_components = 3;</code> */
	private $registered_components;

	/** Generated from protobuf field <code>map<string, string> extended_metadata = 4;</code> */
	private $extended_metadata;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $id
	 *     @type \Dapr\Proto\Runtime\V1\ActiveActorsCount[]|\Google\Protobuf\Internal\RepeatedField $active_actors_count
	 *     @type \Dapr\Proto\Runtime\V1\RegisteredComponents[]|\Google\Protobuf\Internal\RepeatedField $registered_components
	 *     @type array|\Google\Protobuf\Internal\MapField $extended_metadata
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @return string
	 */
	public function getId(): string
	{
		return $this->id;
	}


	/**
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setId(string $var): GetMetadataResponse
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->id = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.ActiveActorsCount active_actors_count = 2;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getActiveActorsCount(): \Google\Protobuf\Internal\RepeatedField
	{
		return $this->active_actors_count;
	}


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.ActiveActorsCount active_actors_count = 2;</code>
	 * @param \Dapr\Proto\Runtime\V1\ActiveActorsCount[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setActiveActorsCount(array|\Google\Protobuf\Internal\RepeatedField $var): GetMetadataResponse
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dapr\Proto\Runtime\V1\ActiveActorsCount::class);
		$this->active_actors_count = $arr;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.RegisteredComponents registered_components = 3;</code>
	 * @return \Google\Protobuf\Internal\RepeatedField
	 */
	public function getRegisteredComponents(): \Google\Protobuf\Internal\RepeatedField
	{
		return $this->registered_components;
	}


	/**
	 * Generated from protobuf field <code>repeated .dapr.proto.runtime.v1.RegisteredComponents registered_components = 3;</code>
	 * @param \Dapr\Proto\Runtime\V1\RegisteredComponents[]|\Google\Protobuf\Internal\RepeatedField $var
	 * @return $this
	 */
	public function setRegisteredComponents(array|\Google\Protobuf\Internal\RepeatedField $var): GetMetadataResponse
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dapr\Proto\Runtime\V1\RegisteredComponents::class);
		$this->registered_components = $arr;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>map<string, string> extended_metadata = 4;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getExtendedMetadata(): \Google\Protobuf\Internal\MapField
	{
		return $this->extended_metadata;
	}


	/**
	 * Generated from protobuf field <code>map<string, string> extended_metadata = 4;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setExtendedMetadata(array|\Google\Protobuf\Internal\MapField $var): GetMetadataResponse
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
		$this->extended_metadata = $arr;

		return $this;
	}
}
