<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * GetSecretRequest is the message to get secret from secret store.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.GetSecretRequest</code>
 */
class GetSecretRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * The name of secret store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 */
	protected $store_name = '';

	/**
	 * The name of secret key.
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 */
	protected $key = '';

	/**
	 * The metadata which will be sent to secret store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 */
	private $metadata;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $store_name
	 *           The name of secret store.
	 *     @type string $key
	 *           The name of secret key.
	 *     @type array|\Google\Protobuf\Internal\MapField $metadata
	 *           The metadata which will be sent to secret store components.
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * The name of secret store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @return string
	 */
	public function getStoreName(): string
	{
		return $this->store_name;
	}


	/**
	 * The name of secret store.
	 *
	 * Generated from protobuf field <code>string store_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setStoreName(string $var): GetSecretRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->store_name = $var;

		return $this;
	}


	/**
	 * The name of secret key.
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @return string
	 */
	public function getKey(): string
	{
		return $this->key;
	}


	/**
	 * The name of secret key.
	 *
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey(string $var): GetSecretRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->key = $var;

		return $this;
	}


	/**
	 * The metadata which will be sent to secret store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata(): \Google\Protobuf\Internal\MapField
	{
		return $this->metadata;
	}


	/**
	 * The metadata which will be sent to secret store components.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 3;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata(array|\Google\Protobuf\Internal\MapField $var): GetSecretRequest
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
		$this->metadata = $arr;

		return $this;
	}
}
