<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * InvokeBindingResponse is the message returned from an output binding invocation
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeBindingResponse</code>
 */
class InvokeBindingResponse extends \Google\Protobuf\Internal\Message
{
	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 */
	protected $data = '';

	/**
	 * The metadata returned from an external system
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 */
	private $metadata;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $data
	 *           The data which will be sent to output binding.
	 *     @type array|\Google\Protobuf\Internal\MapField $metadata
	 *           The metadata returned from an external system
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @return string
	 */
	public function getData(): string
	{
		return $this->data;
	}


	/**
	 * The data which will be sent to output binding.
	 *
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData(string $var): InvokeBindingResponse
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, False);
		$this->data = $var;

		return $this;
	}


	/**
	 * The metadata returned from an external system
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata(): \Google\Protobuf\Internal\MapField
	{
		return $this->metadata;
	}


	/**
	 * The metadata returned from an external system
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata(array|\Google\Protobuf\Internal\MapField $var): InvokeBindingResponse
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
		$this->metadata = $arr;

		return $this;
	}
}
