<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * InvokeServiceRequest represents the request message for Service invocation.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeServiceRequest</code>
 */
class InvokeServiceRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * Required. Callee's app id.
	 *
	 * Generated from protobuf field <code>string id = 1;</code>
	 */
	protected $id = '';

	/**
	 * Required. message which will be delivered to callee.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
	 */
	protected $message;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $id
	 *           Required. Callee's app id.
	 *     @type \Dapr\Proto\Common\V1\InvokeRequest $message
	 *           Required. message which will be delivered to callee.
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Required. Callee's app id.
	 *
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @return string
	 */
	public function getId(): string
	{
		return $this->id;
	}


	/**
	 * Required. Callee's app id.
	 *
	 * Generated from protobuf field <code>string id = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setId(string $var): InvokeServiceRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->id = $var;

		return $this;
	}


	/**
	 * Required. message which will be delivered to callee.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
	 * @return \Dapr\Proto\Common\V1\InvokeRequest|null
	 */
	public function getMessage(): \Dapr\Proto\Common\V1\InvokeRequest|null
	{
		return isset($this->message) ? $this->message : null;
	}


	public function hasMessage(): bool
	{
		return isset($this->message);
	}


	public function clearMessage(): void
	{
		unset($this->message);
	}


	/**
	 * Required. message which will be delivered to callee.
	 *
	 * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
	 * @param \Dapr\Proto\Common\V1\InvokeRequest $var
	 * @return $this
	 */
	public function setMessage(\Dapr\Proto\Common\V1\InvokeRequest $var): InvokeServiceRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkMessage($var, \Dapr\Proto\Common\V1\InvokeRequest::class);
		$this->message = $var;

		return $this;
	}
}
