<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * InvokeActorResponse is the method that returns an actor invocation response.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeActorResponse</code>
 */
class InvokeActorResponse extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>bytes data = 1;</code> */
	protected $data = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $data
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @return string
	 */
	public function getData(): string
	{
		return $this->data;
	}


	/**
	 * Generated from protobuf field <code>bytes data = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData(string $var): InvokeActorResponse
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, False);
		$this->data = $var;

		return $this;
	}
}
