<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/runtime/v1/dapr.proto

namespace Dapr\Proto\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * InvokeServiceRequest represents the request message for Service invocation.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeServiceRequest</code>
 */
class InvokeServiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Callee's app id.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Required. message which will be delivered to callee.
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
     */
    protected $message = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Required. Callee's app id.
     *     @type \Dapr\Proto\Common\V1\InvokeRequest $message
     *           Required. message which will be delivered to callee.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Callee's app id.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Required. Callee's app id.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Required. message which will be delivered to callee.
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
     * @return \Dapr\Proto\Common\V1\InvokeRequest
     */
    public function getMessage()
    {
        return isset($this->message) ? $this->message : null;
    }

    public function hasMessage()
    {
        return isset($this->message);
    }

    public function clearMessage()
    {
        unset($this->message);
    }

    /**
     * Required. message which will be delivered to callee.
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.InvokeRequest message = 3;</code>
     * @param \Dapr\Proto\Common\V1\InvokeRequest $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkMessage($var, \Dapr\Proto\Common\V1\InvokeRequest::class);
        $this->message = $var;

        return $this;
    }

}

