<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * InvokeActorRequest is the message to call an actor.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.InvokeActorRequest</code>
 */
class InvokeActorRequest extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string actor_type = 1;</code> */
	protected $actor_type = '';

	/** Generated from protobuf field <code>string actor_id = 2;</code> */
	protected $actor_id = '';

	/** Generated from protobuf field <code>string method = 3;</code> */
	protected $method = '';

	/** Generated from protobuf field <code>bytes data = 4;</code> */
	protected $data = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $actor_type
	 *     @type string $actor_id
	 *     @type string $method
	 *     @type string $data
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType(): string
	{
		return $this->actor_type;
	}


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType(string $var): InvokeActorRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->actor_type = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId(): string
	{
		return $this->actor_id;
	}


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId(string $var): InvokeActorRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->actor_id = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string method = 3;</code>
	 * @return string
	 */
	public function getMethod(): string
	{
		return $this->method;
	}


	/**
	 * Generated from protobuf field <code>string method = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setMethod(string $var): InvokeActorRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->method = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>bytes data = 4;</code>
	 * @return string
	 */
	public function getData(): string
	{
		return $this->data;
	}


	/**
	 * Generated from protobuf field <code>bytes data = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData(string $var): InvokeActorRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, False);
		$this->data = $var;

		return $this;
	}
}
