<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * PublishEventRequest is the message to publish event data to pubsub topic
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.PublishEventRequest</code>
 */
class PublishEventRequest extends \Google\Protobuf\Internal\Message
{
	/**
	 * The name of the pubsub component
	 *
	 * Generated from protobuf field <code>string pubsub_name = 1;</code>
	 */
	protected $pubsub_name = '';

	/**
	 * The pubsub topic
	 *
	 * Generated from protobuf field <code>string topic = 2;</code>
	 */
	protected $topic = '';

	/**
	 * The data which will be published to topic.
	 *
	 * Generated from protobuf field <code>bytes data = 3;</code>
	 */
	protected $data = '';

	/**
	 * The content type for the data (optional).
	 *
	 * Generated from protobuf field <code>string data_content_type = 4;</code>
	 */
	protected $data_content_type = '';

	/**
	 * The metadata passing to pub components
	 *
	 * metadata property:
	 * - key : the key of the message.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 */
	private $metadata;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $pubsub_name
	 *           The name of the pubsub component
	 *     @type string $topic
	 *           The pubsub topic
	 *     @type string $data
	 *           The data which will be published to topic.
	 *     @type string $data_content_type
	 *           The content type for the data (optional).
	 *     @type array|\Google\Protobuf\Internal\MapField $metadata
	 *           The metadata passing to pub components
	 *
	 *           metadata property:
	 *           - key : the key of the message.
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * The name of the pubsub component
	 *
	 * Generated from protobuf field <code>string pubsub_name = 1;</code>
	 * @return string
	 */
	public function getPubsubName(): string
	{
		return $this->pubsub_name;
	}


	/**
	 * The name of the pubsub component
	 *
	 * Generated from protobuf field <code>string pubsub_name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPubsubName(string $var): PublishEventRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->pubsub_name = $var;

		return $this;
	}


	/**
	 * The pubsub topic
	 *
	 * Generated from protobuf field <code>string topic = 2;</code>
	 * @return string
	 */
	public function getTopic(): string
	{
		return $this->topic;
	}


	/**
	 * The pubsub topic
	 *
	 * Generated from protobuf field <code>string topic = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setTopic(string $var): PublishEventRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->topic = $var;

		return $this;
	}


	/**
	 * The data which will be published to topic.
	 *
	 * Generated from protobuf field <code>bytes data = 3;</code>
	 * @return string
	 */
	public function getData(): string
	{
		return $this->data;
	}


	/**
	 * The data which will be published to topic.
	 *
	 * Generated from protobuf field <code>bytes data = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData(string $var): PublishEventRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, False);
		$this->data = $var;

		return $this;
	}


	/**
	 * The content type for the data (optional).
	 *
	 * Generated from protobuf field <code>string data_content_type = 4;</code>
	 * @return string
	 */
	public function getDataContentType(): string
	{
		return $this->data_content_type;
	}


	/**
	 * The content type for the data (optional).
	 *
	 * Generated from protobuf field <code>string data_content_type = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setDataContentType(string $var): PublishEventRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->data_content_type = $var;

		return $this;
	}


	/**
	 * The metadata passing to pub components
	 *
	 * metadata property:
	 * - key : the key of the message.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getMetadata(): \Google\Protobuf\Internal\MapField
	{
		return $this->metadata;
	}


	/**
	 * The metadata passing to pub components
	 *
	 * metadata property:
	 * - key : the key of the message.
	 *
	 * Generated from protobuf field <code>map<string, string> metadata = 5;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setMetadata(array|\Google\Protobuf\Internal\MapField $var): PublishEventRequest
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
		$this->metadata = $arr;

		return $this;
	}
}
