<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * RegisterActorReminderRequest is the message to register a reminder for an actor of a given type and id.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.RegisterActorReminderRequest</code>
 */
class RegisterActorReminderRequest extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string actor_type = 1;</code> */
	protected $actor_type = '';

	/** Generated from protobuf field <code>string actor_id = 2;</code> */
	protected $actor_id = '';

	/** Generated from protobuf field <code>string name = 3;</code> */
	protected $name = '';

	/** Generated from protobuf field <code>string due_time = 4;</code> */
	protected $due_time = '';

	/** Generated from protobuf field <code>string period = 5;</code> */
	protected $period = '';

	/** Generated from protobuf field <code>bytes data = 6;</code> */
	protected $data = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $actor_type
	 *     @type string $actor_id
	 *     @type string $name
	 *     @type string $due_time
	 *     @type string $period
	 *     @type string $data
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType(): string
	{
		return $this->actor_type;
	}


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType(string $var): RegisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->actor_type = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId(): string
	{
		return $this->actor_id;
	}


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId(string $var): RegisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->actor_id = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @return string
	 */
	public function getName(): string
	{
		return $this->name;
	}


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName(string $var): RegisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string due_time = 4;</code>
	 * @return string
	 */
	public function getDueTime(): string
	{
		return $this->due_time;
	}


	/**
	 * Generated from protobuf field <code>string due_time = 4;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setDueTime(string $var): RegisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->due_time = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string period = 5;</code>
	 * @return string
	 */
	public function getPeriod(): string
	{
		return $this->period;
	}


	/**
	 * Generated from protobuf field <code>string period = 5;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setPeriod(string $var): RegisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->period = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>bytes data = 6;</code>
	 * @return string
	 */
	public function getData(): string
	{
		return $this->data;
	}


	/**
	 * Generated from protobuf field <code>bytes data = 6;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setData(string $var): RegisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, False);
		$this->data = $var;

		return $this;
	}
}
