<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * Generated from protobuf message <code>dapr.proto.runtime.v1.RegisteredComponents</code>
 */
class RegisteredComponents extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string name = 1;</code> */
	protected $name = '';

	/** Generated from protobuf field <code>string type = 2;</code> */
	protected $type = '';

	/** Generated from protobuf field <code>string version = 3;</code> */
	protected $version = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $name
	 *     @type string $type
	 *     @type string $version
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string name = 1;</code>
	 * @return string
	 */
	public function getName(): string
	{
		return $this->name;
	}


	/**
	 * Generated from protobuf field <code>string name = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName(string $var): RegisteredComponents
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string type = 2;</code>
	 * @return string
	 */
	public function getType(): string
	{
		return $this->type;
	}


	/**
	 * Generated from protobuf field <code>string type = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setType(string $var): RegisteredComponents
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->type = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string version = 3;</code>
	 * @return string
	 */
	public function getVersion(): string
	{
		return $this->version;
	}


	/**
	 * Generated from protobuf field <code>string version = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setVersion(string $var): RegisteredComponents
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->version = $var;

		return $this;
	}
}
