<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * SecretResponse is a map of decrypted string/string values
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.SecretResponse</code>
 */
class SecretResponse extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>map<string, string> secrets = 1;</code> */
	private $secrets;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type array|\Google\Protobuf\Internal\MapField $secrets
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>map<string, string> secrets = 1;</code>
	 * @return \Google\Protobuf\Internal\MapField
	 */
	public function getSecrets(): \Google\Protobuf\Internal\MapField
	{
		return $this->secrets;
	}


	/**
	 * Generated from protobuf field <code>map<string, string> secrets = 1;</code>
	 * @param array|\Google\Protobuf\Internal\MapField $var
	 * @return $this
	 */
	public function setSecrets(array|\Google\Protobuf\Internal\MapField $var): SecretResponse
	{
		$arr = \Google\Protobuf\Internal\GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
		$this->secrets = $arr;

		return $this;
	}
}
