<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * Generated from protobuf message <code>dapr.proto.runtime.v1.SetMetadataRequest</code>
 */
class SetMetadataRequest extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string key = 1;</code> */
	protected $key = '';

	/** Generated from protobuf field <code>string value = 2;</code> */
	protected $value = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $key
	 *     @type string $value
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @return string
	 */
	public function getKey(): string
	{
		return $this->key;
	}


	/**
	 * Generated from protobuf field <code>string key = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey(string $var): SetMetadataRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->key = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string value = 2;</code>
	 * @return string
	 */
	public function getValue(): string
	{
		return $this->value;
	}


	/**
	 * Generated from protobuf field <code>string value = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setValue(string $var): SetMetadataRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->value = $var;

		return $this;
	}
}
