<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/runtime/v1/dapr.proto

namespace Dapr\Proto\Runtime\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TransactionalStateOperation is the message to execute a specified operation with a key-value pair.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.TransactionalStateOperation</code>
 */
class TransactionalStateOperation extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of operation to be executed
     *
     * Generated from protobuf field <code>string operationType = 1;</code>
     */
    protected $operationType = '';
    /**
     * State values to be operated on 
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.StateItem request = 2;</code>
     */
    protected $request = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $operationType
     *           The type of operation to be executed
     *     @type \Dapr\Proto\Common\V1\StateItem $request
     *           State values to be operated on 
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of operation to be executed
     *
     * Generated from protobuf field <code>string operationType = 1;</code>
     * @return string
     */
    public function getOperationType()
    {
        return $this->operationType;
    }

    /**
     * The type of operation to be executed
     *
     * Generated from protobuf field <code>string operationType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationType($var)
    {
        GPBUtil::checkString($var, True);
        $this->operationType = $var;

        return $this;
    }

    /**
     * State values to be operated on 
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.StateItem request = 2;</code>
     * @return \Dapr\Proto\Common\V1\StateItem
     */
    public function getRequest()
    {
        return isset($this->request) ? $this->request : null;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * State values to be operated on 
     *
     * Generated from protobuf field <code>.dapr.proto.common.v1.StateItem request = 2;</code>
     * @param \Dapr\Proto\Common\V1\StateItem $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Dapr\Proto\Common\V1\StateItem::class);
        $this->request = $var;

        return $this;
    }

}

