<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * TransactionalAcorStateOperation is the message to execute a specified operation with a key-value pair.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.TransactionalActorStateOperation</code>
 */
class TransactionalActorStateOperation extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string operationType = 1;</code> */
	protected $operationType = '';

	/** Generated from protobuf field <code>string key = 2;</code> */
	protected $key = '';

	/** Generated from protobuf field <code>.google.protobuf.Any value = 3;</code> */
	protected $value;


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $operationType
	 *     @type string $key
	 *     @type \Google\Protobuf\Any $value
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string operationType = 1;</code>
	 * @return string
	 */
	public function getOperationType(): string
	{
		return $this->operationType;
	}


	/**
	 * Generated from protobuf field <code>string operationType = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setOperationType(string $var): TransactionalActorStateOperation
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->operationType = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @return string
	 */
	public function getKey(): string
	{
		return $this->key;
	}


	/**
	 * Generated from protobuf field <code>string key = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setKey(string $var): TransactionalActorStateOperation
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->key = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>.google.protobuf.Any value = 3;</code>
	 * @return \Google\Protobuf\Any|null
	 */
	public function getValue(): \Google\Protobuf\Any|null
	{
		return isset($this->value) ? $this->value : null;
	}


	public function hasValue(): bool
	{
		return isset($this->value);
	}


	public function clearValue(): void
	{
		unset($this->value);
	}


	/**
	 * Generated from protobuf field <code>.google.protobuf.Any value = 3;</code>
	 * @param \Google\Protobuf\Any $var
	 * @return $this
	 */
	public function setValue(\Google\Protobuf\Any $var): TransactionalActorStateOperation
	{
		\Google\Protobuf\Internal\GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
		$this->value = $var;

		return $this;
	}
}
