<?php

/**
 * This file is automatically generated by `composer build-grpc`
 */

namespace Dapr\Proto\Runtime\V1;

/**
 * UnregisterActorReminderRequest is the message to unregister an actor reminder.
 *
 * Generated from protobuf message <code>dapr.proto.runtime.v1.UnregisterActorReminderRequest</code>
 */
class UnregisterActorReminderRequest extends \Google\Protobuf\Internal\Message
{
	/** Generated from protobuf field <code>string actor_type = 1;</code> */
	protected $actor_type = '';

	/** Generated from protobuf field <code>string actor_id = 2;</code> */
	protected $actor_id = '';

	/** Generated from protobuf field <code>string name = 3;</code> */
	protected $name = '';


	/**
	 * Constructor.
	 *
	 * @param array $data {
	 *     Optional. Data for populating the Message object.
	 *
	 *     @type string $actor_type
	 *     @type string $actor_id
	 *     @type string $name
	 * }
	 */
	public function __construct(array|null $data = null)
	{
		\GPBMetadata\Dapr\Proto\Runtime\V1\Dapr::initOnce();
		parent::__construct($data);
	}


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @return string
	 */
	public function getActorType(): string
	{
		return $this->actor_type;
	}


	/**
	 * Generated from protobuf field <code>string actor_type = 1;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorType(string $var): UnregisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->actor_type = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @return string
	 */
	public function getActorId(): string
	{
		return $this->actor_id;
	}


	/**
	 * Generated from protobuf field <code>string actor_id = 2;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setActorId(string $var): UnregisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->actor_id = $var;

		return $this;
	}


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @return string
	 */
	public function getName(): string
	{
		return $this->name;
	}


	/**
	 * Generated from protobuf field <code>string name = 3;</code>
	 * @param string $var
	 * @return $this
	 */
	public function setName(string $var): UnregisterActorReminderRequest
	{
		\Google\Protobuf\Internal\GPBUtil::checkString($var, True);
		$this->name = $var;

		return $this;
	}
}
