apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: client-service
  name: client
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: client-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: client
        dapr.io/app-port: "80"
        dapr.io/max-concurrency: "100"
    spec:
      containers:
        - image: ${DOCKER_USER}/php-client-service:latest
          name: client
          imagePullPolicy: Always
        - image: ${DOCKER_USER}/php-client-http:latest
          name: client-http
          imagePullPolicy: Always
