apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: secrets-service
  name: secrets
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: secrets-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secrets-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: secrets
        dapr.io/app-port: "80"
        dapr.io/max-concurrency: "100"
    spec:
      containers:
        - image: ${DOCKER_USER}/php-secrets-service:latest
          name: secrets
          imagePullPolicy: Always
        - image: ${DOCKER_USER}/php-secrets-http:latest
          name: secrets-http
          imagePullPolicy: Always
